In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

# import data_cleaning as dc
# import models as rm

from sklearn import metrics
from sklearn.metrics import mean_squared_error, mean_squared_log_error
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.outliers_influence import variance_inflation_factor

import scipy.stats as stats

%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
df = pd.read_csv('data/products_final.csv')

In [3]:
df.head()

,Unnamed: 0,order_status,payment_sequential,payment_type,payment_installments,review_score,customer_zip_code_prefix,customer_city,customer_state,price,...,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,0,2,1,1,1.0,4.0,3149.0,3576,25,29.99,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,325,22
1,1,2,2,3,1.0,4.0,3149.0,3576,25,29.99,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,325,22
2,2,2,3,3,1.0,4.0,3149.0,3576,25,29.99,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,325,22
3,3,2,1,0,1.0,4.0,47813.0,416,4,118.70,...,29.0,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,63,22
4,4,2,1,1,3.0,5.0,75265.0,4027,8,159.90,...,46.0,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,217,22

In [4]:
df.columns

Index(['Unnamed: 0', 'order_status', 'payment_sequential', 'payment_type',
       'payment_installments', 'review_score', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'price', 'freight_value',
       'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'seller_zip_code_prefix',
       'seller_city', 'seller_state'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116577 entries, 0 to 116576
Data columns (total 21 columns):
Unnamed: 0                    116577 non-null int64
order_status                  116577 non-null int64
payment_sequential            116577 non-null int64
payment_type                  116577 non-null int64
payment_installments          116577 non-null float64
review_score                  116577 non-null float64
customer_zip_code_prefix      116577 non-null float64
customer_city                 116577 non-null int64
customer_state                116577 non-null int64
price                         116577 non-null float64
freight_value                 116577 non-null float64
product_name_lenght           116577 non-null float64
product_description_lenght    116577 non-null float64
product_photos_qty            116577 non-null float64
product_weight_g              116577 non-null float64
product_length_cm             116577 non-null float64
product_height_cm             116577 non-null float64
product_width_cm              116577 non-null float64
seller_zip_code_prefix        116577 non-null float64
seller_city                   116577 non-null int64
seller_state                  116577 non-null int64
dtypes: float64(13), int64(8)
memory usage: 18.7 MB

In [ ]:
lst = ['seller_city','seller_state','seller_zip_code_prefix']

for x in lst:
    df[x] = df[x].astype('category')

In [ ]:
lst = ['seller_city','seller_state','seller_zip_code_prefix']

for x in lst:
    df[x] = labelencoder.fit_transform(df[x])



df['genre'] = labelencoder.fit_transform(df['genre'])
df['explicit'] = labelencoder.fit_transform(df['explicit'])
df['key'] = labelencoder.fit_transform(df['key'])
df['mode'] = labelencoder.fit_transform(df['mode'])
df['time_signature'] = labelencoder.fit_transform(df['time_signature'])

In [ ]:
df_dum = pd.get_dummies(df[['key','mode','year', 'explicit','time_signature']])